#!/usr/bin/env node
'use strict';

const readline = require('readline');
const fs = require('fs');
const path = require('path');

const OUT = path.resolve(__dirname, '..', '.env');

if (fs.existsSync(OUT)) {
  const backup = `${OUT}.bak`;
  fs.copyFileSync(OUT, backup);
  console.log(`Existing .env backed up to ${backup}`);
}

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

function ask(question, defaultValue = '') {
  const hint = defaultValue ? ` [${defaultValue}]` : '';
  return new Promise((resolve) => {
    rl.question(`${question}${hint}: `, (answer) => {
      resolve(answer.trim() || defaultValue);
    });
  });
}

function askBool(question, defaultValue = false) {
  const hint = defaultValue ? '[Y/n]' : '[y/N]';
  return new Promise((resolve) => {
    rl.question(`${question} ${hint}: `, (answer) => {
      const a = answer.trim().toLowerCase();
      if (!a) resolve(defaultValue);
      else resolve(a === 'y' || a === 'yes' || a === 'true');
    });
  });
}

async function main() {
  console.log('\n=== Live Caption Engine — config generator ===\n');

  // ── Engine ──────────────────────────────────────────────────────────────────
  const engine = (await ask('Engine (soniox / gemini)', 'soniox')).toLowerCase();

  let sonioxApiKey = '', sonioxModel = '', sonioxWsUrl = '';
  let geminiApiKey = '', geminiModel = '';

  if (engine === 'soniox') {
    sonioxApiKey = await ask('SONIOX_API_KEY');
    sonioxModel  = await ask('SONIOX_MODEL', 'stt-rt-preview');
    sonioxWsUrl  = await ask('SONIOX_WS_URL', 'wss://stt-rt.soniox.com/transcribe-websocket');
  } else {
    geminiApiKey = await ask('GEMINI_API_KEY');
    geminiModel  = await ask('GEMINI_MODEL', 'gemini-2.0-flash-live-001');
  }

  // ── Stream ───────────────────────────────────────────────────────────────────
  console.log('');
  const rtmpUrl    = await ask('RTMP_URL', 'rtmp://host.docker.internal/live/stream');
  const sampleRate = await ask('AUDIO_SAMPLE_RATE', '16000');
  const channels   = await ask('AUDIO_CHANNELS', '1');

  // ── Translation ───────────────────────────────────────────────────────────────
  console.log('');
  const enableTranslation = await askBool('Enable translation?', false);
  let sourceLang = '', targetLangs = 'en', translationType = 'one_way';
  if (enableTranslation) {
    sourceLang       = await ask('Source language BCP-47 (empty = auto-detect)', '');
    targetLangs      = await ask('Target languages (comma-separated BCP-47)', 'en');
    translationType  = await ask('Translation type (one_way / two_way)', 'one_way');
  }

  // ── Captions ──────────────────────────────────────────────────────────────────
  console.log('');
  const captionsEnabled     = await askBool('Enable local caption HTTP endpoints?', true);
  const segmentDurationMs   = await ask('Caption segment duration ms', '6000');
  const windowSegments      = await ask('Caption window segments (in-memory)', '5');

  // ── MediaPackage ─────────────────────────────────────────────────────────────
  console.log('');
  const mpEnabled = await askBool('Push captions to MediaPackage V2?', false);
  let mpIngestUrl = '', mpRegion = 'us-east-1', mpSubPath = 'subtitles', mpTransSubPath = 'subtitles-translated';
  if (mpEnabled) {
    mpIngestUrl    = await ask('MEDIAPACKAGE_INGEST_URL');
    mpRegion       = await ask('AWS_REGION', 'us-east-1');
    mpSubPath      = await ask('MEDIAPACKAGE_SUBTITLE_PATH', 'subtitles');
    if (enableTranslation) {
      mpTransSubPath = await ask('MEDIAPACKAGE_TRANSLATION_SUBTITLE_PATH', 'subtitles-translated');
    }
  }

  // ── App ───────────────────────────────────────────────────────────────────────
  console.log('');
  const port     = await ask('PORT', '8080');
  const logLevel = await ask('LOG_LEVEL (trace/debug/info/warn/error)', 'info');

  rl.close();

  // ── Write ─────────────────────────────────────────────────────────────────────
  const lines = [
    '# Generated by scripts/generate-config.js',
    '',
    '# Engine',
    `ENGINE=${engine}`,
    '',
  ];

  if (engine === 'soniox') {
    lines.push('# Soniox');
    lines.push(`SONIOX_API_KEY=${sonioxApiKey}`);
    lines.push(`SONIOX_MODEL=${sonioxModel}`);
    lines.push(`SONIOX_WS_URL=${sonioxWsUrl}`);
  } else {
    lines.push('# Gemini Live API');
    lines.push(`GEMINI_API_KEY=${geminiApiKey}`);
    lines.push(`GEMINI_MODEL=${geminiModel}`);
  }

  lines.push('');
  lines.push('# Stream');
  lines.push(`RTMP_URL=${rtmpUrl}`);
  lines.push(`AUDIO_SAMPLE_RATE=${sampleRate}`);
  lines.push(`AUDIO_CHANNELS=${channels}`);
  lines.push('FFMPEG_PATH=ffmpeg');
  lines.push('');
  lines.push('# Resiliency');
  lines.push('NO_AUDIO_TIMEOUT_MS=15000');
  lines.push('RECONNECT_DELAY_MS=3000');
  lines.push('MAX_RETRIES=0');
  lines.push('');
  lines.push('# Translation');
  lines.push(`ENABLE_TRANSLATION=${enableTranslation}`);
  lines.push(`TRANSLATION_TYPE=${translationType}`);
  lines.push(`TRANSLATION_SOURCE_LANGUAGE=${sourceLang}`);
  lines.push(`TRANSLATION_TARGET_LANGUAGES=${targetLangs}`);
  lines.push('');
  lines.push('# Captions');
  lines.push(`CAPTIONS_ENABLED=${captionsEnabled}`);
  lines.push(`CAPTIONS_SEGMENT_DURATION_MS=${segmentDurationMs}`);
  lines.push(`CAPTIONS_WINDOW_SEGMENTS=${windowSegments}`);
  lines.push('CAPTIONS_BASE_PATH=/captions');
  lines.push('');
  lines.push('# MediaPackage V2');
  lines.push(`MEDIAPACKAGE_ENABLED=${mpEnabled}`);
  lines.push(`MEDIAPACKAGE_INGEST_URL=${mpIngestUrl}`);
  lines.push(`MEDIAPACKAGE_SUBTITLE_PATH=${mpSubPath}`);
  lines.push(`MEDIAPACKAGE_TRANSLATION_SUBTITLE_PATH=${mpTransSubPath}`);
  lines.push(`AWS_REGION=${mpRegion}`);
  lines.push('');
  lines.push('# App server');
  lines.push(`PORT=${port}`);
  lines.push(`LOG_LEVEL=${logLevel}`);

  fs.writeFileSync(OUT, lines.join('\n') + '\n', 'utf8');
  console.log(`\n.env written to ${OUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
